### ISSUE TITLE
Erros F.A.Q

### ISSUE THREAD

**Issue by UlisesGascon** [GoblinDBRocks/GoblinDB#14]
To include F.A.Q just for errors details, link to the documentation to be added to the scripts.

**Comment by CodingCarlos** [comment]
We'd better fix #13 before this, but with this on mind (just commenting to link the issues)

**Comment by CodingCarlos** [comment]
Moved to 0.1.0, because I think v0.0.x does not need this, but now that everything is being refactored, might be a good thing for the v0.1.x

**Comment by drewler** [comment]
Added [error messages to the wiki](https://github.com/GoblinDBRocks/GoblinDB/wiki/Errors). Each error description can be expanded as project progesses, to provide a more 'philosophical' or detailed explanation.

Also, by applying #46, error messages when running in development mode will provide a link to the correspoding error in the wiki.

**Comment by Sediug** [comment]
Thanks @drewler I'm gonna close this issue an Open a new one for version 2, Improve the wiki FAQ page jaja :+1:
