### ISSUE TITLE
File update Error

### ISSUE THREAD

**Issue by CodingCarlos** [GoblinDBRocks/GoblinDB#22]
Sometimes, the goblin_db.json gets corrupted on update. This happens when there is data in the file (i.e. last execution stored stuff) and open again the database. On doing a .set, it store it as a new json at the end of the actual one, instead of load the previous data, add the new value, and store it all together.

I'm now trying to create some code snippet to reproduce it, but the ressult is this:
```json
{"User_5":{"name":"Paco","id":5}}"User_8":{"name":"Paco","id":8}}
```
instead of this:
```json
{"User_5":{"name":"Paco","id":5},"User_8":{"name":"Paco","id":8}}
```

**Comment by UlisesGascon** [comment]
Thanks for share it, @CodingCarlos! I detected a similar issue in the pass with Ambush functions. The workaround solution was to [flush the content before save the changes](https://github.com/GoblinDBRocks/GoblinDB/blob/master/goblin.js#L56)...

Do you want to replicate the solution for database too?
