### ISSUE TITLE
Add error events.

### ISSUE THREAD

**Issue by Sediug** [GoblinDBRocks/GoblinDB#37]
For production mode or even for everytime an error happen (like trying to add an ambush function with an id that belong to an already stored ambush). 

I think this could be usefull specially for production mode. Then you can listen for errors and store logs or whatever you want.

**This should be included into v1.0 Milestone**

**Comment by Sediug** [comment]
A good place to do it could be the [ logger ](https://github.com/GoblinDBRocks/GoblinDB/blob/master/lib/logger/index.js)

**Comment by CodingCarlos** [comment]
Sounds like a great idea!

**Comment by Sediug** [comment]
If we all agree I'd say this may be a good feature to have in vs1 https://github.com/GoblinDBRocks/GoblinDB/milestone/3

**Comment by Sediug** [comment]
Thanks @alvarogtx300 :smile:
