### ISSUE TITLE
Atomic Test

### ISSUE THREAD

**Issue by UlisesGascon** [GoblinDBRocks/GoblinDB#9]
Time to improve the current test in order to respect more de unit testing concept.

**Comment by CodingCarlos** [comment]
@Sediug have done a lot of work on testing in #31. I don't know how far this issue goes, and if actual tests are covering this or not. Maybe a little bit more of info, @UlisesGascon?

**Comment by Sediug** [comment]
I think there is work to do on that matter. Most of the test depend on what you add or delete in the previous test, etc.

**Comment by Sediug** [comment]
Check throw errors - test cases
